version: "3.7"

services:
  plex:
    build:
      context: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dev/media:/data
      - ./dev/config:/config
      - ./dev/transcode:/transcode
    ports:
      - 32400:32400
      - 33400:33400
